#!/bin/bash

{
    echo "input_files/input_s.txt"
    echo "s"
    echo "output.txt"
    echo "d"
} | python floating_point.py > /dev/null

printf "Calling diff on ACTUAL vs EXPECTED output...\n"

diff output.txt expected_outputs/output_d.txt

echo ""
